sudo: required
dist: trusty
language: python
python:
- '2.7'
- '3.5'
before_install:
- wget https://launchpad.net/ubuntu/+source/htslib/1.2.1-2ubuntu1/+build/8443430/+files/tabix_1.2.1-2ubuntu1_amd64.deb
- sudo dpkg -i tabix_1.2.1-2ubuntu1_amd64.deb
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: biocommons
  password:
    secure: vZx3K0KBKK6RKQVUXemp1Pg2Y7dzZh64qfjJerrhuS3oxdqFMAZRrALVy/Hgl48vFT7/E71Yxx5KtjmyCFpN3JokvfhdfShXsKh9AL4c6kUJsFYNPg7FGnY0C1JVgZ+rYjL0rGKJAevRxd59CDWqHpYOl9MZfiFblniFkYjmbfYBzbLhcahycnwlNX1YCGA1ygjAZbAO71CCNTLblOHEZ+SNDbR75oVPZI9qAX0xRztY9NWVYc66ZN6qVEFW2Ez92LvR5t6ybg8chEXZsfD5h6rM8gjgeAgwys6FSpzDXW+ItIpuvZq2ymFROAez+Km4N1ushMoGLhuBWGfvv2WReBYk25MgJbz+rtopi1h3s13gRr2xJhs3JiFmsCPKbUdYunePr0qcuoGOM5R+NV4SATySU1bHAWWAAzHx0jCegYwZQif0W0JWZUlcsffu6+7KJF9YINfmrCeWQp0CSnV7J8+KH3novU9OT7DVNFuwFLJNTun50g3ToGlcvS4x3jWWZKOKFVCBp5tEtOyAXf01Ph6qD97uyO1oVM+1vLiPD2NuGBa0AAlVIXWEIU1gyRDw8m+k0e3F9smjWnanJxwMb+GVr8G7MArFMUqT8MFr2fvrcLxbkMwUbKLu+lI9xRW32+b4fNofkAhZe8cWV0KsEV0vOPw5ql7WYtQ0M5TSKL4=
    oldsecure: ju1rrMvNgzi9LYg8V4X4UE+t5yVIul+j4X8Yxo7Va5i1Soe3/xYn/tD9Q67CHh3qs1cwTEkcnQXve7ehUPcO0KWksapLBFhxyUnaq9XygYyxVEwF+2JXJkqxXjyYub+Ng/ZQmsXEViwalm9GkGNGe3picW0AQEbH+jBeBlOcwrmo9eweW0yHbKFHc+5o9rO5lE0etwPSN1JMicRq6jQvPi0XDlCF9uyusxwCf+Gtk92lJkHRP8HRXmQ+fDFcVp5xGmJrim6hbx4nd51TgdHLq2jF9p579xvzx2yiMZa4GW4HcxA8GAs7IOTqeWsyG1TejhRwxD8Zo0hO81Dm3ftSzemtx+ikgFOq+Tszukp0RO/lMYGMECgHZhIVDPu5Ubmm8fGUsdaf+suIge73yLpr0nf63Id7HQxocjZq0j8In8X3x4Ii8K/PpN2i8mx3op6mjQALvr3NyBq8rsI1BHu86H8bt4SBXY8/oysWm0/9/sUa4jz2bB0yS0qoo9kfx9I6R4ly+qhVifkSntnIe3WXQ0OyL6W7oXpyz+0xQ4P/PJUYcwvu1v2qTwcKbPb3QoI08eqT7nVZ0LWXv7Pye73gWYZdBfPTFd86WVO1ZXHeiFioWU7vKOWsbgSqX6+pBXqlyDdOrgJ2o7SrIYHN52ViOagTOejk8KrcchvWTo4GBxc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: biocommons/seqrepo
    branch: master
